# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XiGuaManHua' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit'
  # Pods for XiGuaManHua

  target 'XiGuaManHuaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XiGuaManHuaUITests' do
    # Pods for testing
  end

end
